config/routes.rb
Rails.application.routes.draw do
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def hello
    render html: "hello, rails world!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstAppPg</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "partials/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/partials/_navbar.erb
<nav>
  <ul>
    <li>
      <%= link_to "Home", root_path %>
    </li>
    <li>
      <%= link_to "Help", help_path %>
    </li>    
    <li>
      <%= link_to "Contact", contact_path %>
    </li>    
    <li>
      <%= link_to "About", about_path %>
    </li>        
  </ul>
</nav>

app/views/static_pages/about.erb
<% provide(:title, "About") %>

<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org"><em>Ruby on Rails Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org">Ruby on Rails</a>.
</p>

app/views/static_pages/contact.erb
<% provide(:title, "Contact") %>

<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href='https://www.railstutorial.org/contact'>Contact Page</a>
</p>

app/views/static_pages/help.erb
<% provide(:title, "Help") %>

<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href='https://www.railstutorial.org/help'>Rails Tutorial help section</a>
  To get help on this sample app, see the
  <a href='https://www.railstutorial.org/book'><em>Rails on Rails Tutorial</em> book</a>
</p>

app/views/static_pages/home.erb
<div class='center jumbotron'>
  <h1>Welcome to the Sample App</h1>
  <h2>
    This is the home page for the
    <a href='http://www.railstutorial.org'>Ruby on Rails Tutorial</a>
    sample application.
  </h2>
  <%=  link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>